import os
import json
import logging
import google.generativeai as genai
from typing import List, Dict, Any, Optional

from services.github_context import format_context_for_prompt

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# System Prompts
# ---------------------------------------------------------------------------

TRIAGE_SYSTEM_PROMPT = """You are Agent 3 (Critic Triage Pruner) for VerifyFix.
Your job is to evaluate candidate vulnerabilities against the full code diff and RAG threat intelligence context.

For each candidate, determine if the vulnerability is truly exploitable or if framework-level mitigations (e.g., ORM usage, parameterized queries, middleware sanitizers, CSRF tokens, Content-Security-Policy headers) neutralize it.

Return ONLY the vulnerabilities that are **confirmed unmitigated** — i.e., the code is genuinely vulnerable and no framework protection exists in the diff.

Return a strict JSON list. Do NOT wrap the JSON in Markdown backticks.
If all candidates are mitigated, return an empty list: []

The JSON schema must exactly match the input schema:
[
  {
    "cwe_id": "CWE-89",
    "vulnerability_name": "SQL Injection",
    "file_path": "routes/auth.py",
    "line_start": 42,
    "line_end": 48,
    "suspect_code": "query = f'SELECT * FROM users WHERE user={user_input}'",
    "reasoning": "Unsanitized user variable concatenated into raw SQL string. No ORM or parameterized query detected in the diff."
  }
]
"""

FIXTURE_SYSTEM_PROMPT = """You are Agent 3 (Critic Fixture Generator) for VerifyFix.
Your job is to generate a standalone, self-contained Python test harness that proves whether a specific vulnerability is exploitable.

CRITICAL RULES:
1. The script MUST be compatible with **Python 3.11**. Do NOT use any Python 3.12+ features (e.g., `type` statements, new-style generic syntax `def foo[T]()`, etc.).
2. The script MUST be completely self-contained — no external dependencies beyond the Python 3.11 standard library.
3. The script MUST set up its own test environment in-memory (e.g., `sqlite3.connect(':memory:')` for SQL injection tests).
4. The script MUST reproduce the vulnerable code path exactly as it appears in the suspect code.
5. The script MUST attempt an exploit payload targeting the specific CWE.
6. On successful exploit, print exactly: [VULNERABILITY_CONFIRMED] followed by evidence, then exit with code 0.
7. If the exploit is blocked/neutralized, print exactly: [SECURE] followed by explanation, then exit with code 0.
8. If an error occurs, let the exception propagate naturally (non-zero exit).
9. Keep the script simple and fast — it should complete execution in under 10 seconds.
10. Do NOT use any sleep(), time delays, or network calls.

Return ONLY the raw Python code. Do NOT wrap it in Markdown backticks or add any explanation.
"""

FIXTURE_SELF_HEAL_PROMPT = """The previous fixture script failed during sandbox execution. Here is the error information:

{error_info}

Please regenerate the fixture script, fixing the issue described above. Follow all the same rules as before:
- Python 3.11 compatible only
- Self-contained, no external dependencies
- Simple and fast (complete in under 10 seconds)
- Print [VULNERABILITY_CONFIRMED] or [SECURE] on success

Return ONLY the raw Python code. Do NOT wrap it in Markdown backticks.
"""


# ---------------------------------------------------------------------------
# Fallback: Hardcoded fixture templates for known CWEs
# ---------------------------------------------------------------------------

FALLBACK_FIXTURES = {
    "CWE-89": '''"""
Auto-generated test fixture for CWE-89: SQL Injection
Generated by VerifyFix Critic Agent (fallback template)
"""
import sqlite3

def create_test_db():
    """Create an in-memory SQLite database with test data."""
    conn = sqlite3.connect(":memory:")
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE users (
            id INTEGER PRIMARY KEY,
            username TEXT NOT NULL,
            role TEXT NOT NULL,
            password_hash TEXT NOT NULL
        )
    """)
    cursor.execute(
        "INSERT INTO users (username, role, password_hash) VALUES (?, ?, ?)",
        ("admin", "superadmin", "hashed_pw_placeholder")
    )
    cursor.execute(
        "INSERT INTO users (username, role, password_hash) VALUES (?, ?, ?)",
        ("testuser", "viewer", "hashed_pw_placeholder")
    )
    conn.commit()
    return conn


def vulnerable_login(conn, username_input: str):
    """Reproduce the vulnerable code path."""
    cursor = conn.cursor()
    query = f"SELECT id, username, role FROM users WHERE username='{username_input}'"
    cursor.execute(query)
    return cursor.fetchall()


def test_sql_injection():
    """Attempt SQL injection payload against the vulnerable function."""
    conn = create_test_db()

    # Benign input — should return single user
    benign_result = vulnerable_login(conn, "testuser")
    assert len(benign_result) == 1, f"Expected 1 row, got {len(benign_result)}"

    # Malicious payload — tautology-based injection
    payload = "' OR '1'='1"
    malicious_result = vulnerable_login(conn, payload)

    if len(malicious_result) > 1:
        print(f"[VULNERABILITY_CONFIRMED] Payload returned {len(malicious_result)} rows (expected 0-1)")
        conn.close()
        return "VULNERABILITY_CONFIRMED"
    else:
        print("[SECURE] Payload was neutralized")
        conn.close()
        return "SECURE"


if __name__ == "__main__":
    result = test_sql_injection()
    print(f"Final verdict: {result}")
    exit(0)
''',
}


# ---------------------------------------------------------------------------
# Triage Pruning
# ---------------------------------------------------------------------------

def run_triage_pruning(
    candidate_vulns: List[Dict[str, Any]],
    rag_context: Dict[str, str],
    diff_text: str,
    full_files: Optional[Dict[str, str]] = None,
    dependency_files: Optional[Dict[str, str]] = None,
) -> List[Dict[str, Any]]:
    """
    Phase I: Evaluate candidate vulnerabilities against framework context.
    In full-context mode, uses complete file sources for deeper triage.
    Returns only the confirmed unmitigated vulnerabilities.
    """
    if not candidate_vulns:
        return []

    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        logger.warning("No GEMINI_API_KEY found. Skipping triage — keeping all candidates.")
        return candidate_vulns

    try:
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel(
            'gemini-3.1-flash-lite',
            system_instruction=TRIAGE_SYSTEM_PROMPT,
            generation_config=genai.types.GenerationConfig(
                temperature=0.2,
                top_p=0.95,
                response_mime_type="application/json",
            ),
        )

        # Build context for the model
        rag_summary = "\n\n".join(
            f"--- {cwe_id} ---\n{context}"
            for cwe_id, context in rag_context.items()
        )

        # Build code context (full or diff-only)
        if full_files:
            code_context = format_context_for_prompt(
                diff_text=diff_text,
                full_files=full_files,
                dependency_files=dependency_files or {},
            )
            code_section = f"## Full Code Context (Changed Files + Dependencies + Diff)\n{code_context}"
        else:
            code_section = f"## Code Diff\n```\n{diff_text}\n```"

        prompt = (
            f"{code_section}\n\n"
            f"## RAG Threat Intelligence Context\n{rag_summary}\n\n"
            f"## Candidate Vulnerabilities\n```json\n{json.dumps(candidate_vulns, indent=2)}\n```\n\n"
            f"Evaluate each candidate. Return ONLY the unmitigated ones as a JSON list."
        )

        response = model.generate_content(prompt)
        result_text = response.text.strip()
        pruned = json.loads(result_text)

        if not isinstance(pruned, list):
            logger.warning(f"Gemini triage returned non-list: {pruned}")
            return candidate_vulns

        logger.info(f"Triage pruning: {len(candidate_vulns)} candidates → {len(pruned)} confirmed")
        return pruned

    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse Gemini triage JSON: {e}")
        return candidate_vulns
    except Exception as e:
        logger.error(f"Gemini API error during triage: {e}")
        return candidate_vulns


# ---------------------------------------------------------------------------
# Fixture Generation
# ---------------------------------------------------------------------------

def run_fixture_generation(
    vuln: Dict[str, Any],
    rag_context: Dict[str, str],
    diff_text: str,
    error_traces: Optional[str] = None,
    full_files: Optional[Dict[str, str]] = None,
    dependency_files: Optional[Dict[str, str]] = None,
) -> str:
    """
    Phase II: Generate a standalone test harness for a specific vulnerability.
    In full-context mode, uses complete file sources for more accurate fixture code.
    If error_traces is provided, incorporates it for self-healing regeneration.
    Returns the generated Python fixture code as a string.
    """
    cwe_id = vuln.get("cwe_id", "UNKNOWN")

    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        logger.warning(f"No GEMINI_API_KEY found. Using fallback fixture for {cwe_id}.")
        return _get_fallback_fixture(cwe_id, vuln)

    try:
        genai.configure(api_key=api_key)

        system_prompt = FIXTURE_SYSTEM_PROMPT
        if error_traces:
            system_prompt += "\n\n" + FIXTURE_SELF_HEAL_PROMPT.format(error_info=error_traces)

        model = genai.GenerativeModel(
            'gemini-3.1-flash-lite',
            system_instruction=system_prompt,
            generation_config=genai.types.GenerationConfig(
                temperature=0.0,
                top_p=0.95,
            ),
        )

        # Build the rag context for this specific CWE
        cwe_context = rag_context.get(cwe_id, "No threat intelligence available.")

        # Build code context
        if full_files:
            code_context = format_context_for_prompt(
                diff_text=diff_text,
                full_files=full_files,
                dependency_files=dependency_files or {},
            )
            code_section = f"## Full Code Context\n{code_context}"
        else:
            code_section = f"## Original Code Diff\n```\n{diff_text}\n```"

        prompt = (
            f"Generate a test harness for the following vulnerability:\n\n"
            f"## Vulnerability Details\n"
            f"- CWE: {cwe_id} ({vuln.get('vulnerability_name', 'Unknown')})\n"
            f"- File: {vuln.get('file_path', 'unknown')}\n"
            f"- Lines: {vuln.get('line_start', '?')}-{vuln.get('line_end', '?')}\n"
            f"- Suspect Code: {vuln.get('suspect_code', 'N/A')}\n"
            f"- Reasoning: {vuln.get('reasoning', 'N/A')}\n\n"
            f"{code_section}\n\n"
            f"## Threat Intelligence ({cwe_id})\n{cwe_context}\n\n"
            f"Generate the Python 3.11 compatible test harness now."
        )

        response = model.generate_content(prompt)
        fixture_code = response.text.strip()

        # Strip markdown code fences if Gemini wrapped them anyway
        if fixture_code.startswith("```python"):
            fixture_code = fixture_code[len("```python"):].strip()
        if fixture_code.startswith("```"):
            fixture_code = fixture_code[3:].strip()
        if fixture_code.endswith("```"):
            fixture_code = fixture_code[:-3].strip()

        logger.info(f"Generated fixture for {cwe_id}: {len(fixture_code)} chars")
        return fixture_code

    except Exception as e:
        logger.error(f"Gemini API error during fixture generation for {cwe_id}: {e}")
        return _get_fallback_fixture(cwe_id, vuln)


def _get_fallback_fixture(cwe_id: str, vuln: Dict[str, Any]) -> str:
    """Return a hardcoded fallback fixture template for known CWEs."""
    if cwe_id in FALLBACK_FIXTURES:
        logger.info(f"Using fallback fixture template for {cwe_id}")
        return FALLBACK_FIXTURES[cwe_id]

    # Generic fallback for unknown CWEs
    logger.warning(f"No fallback fixture template for {cwe_id}. Using generic stub.")
    return f'''"""
Auto-generated generic test fixture for {cwe_id}: {vuln.get("vulnerability_name", "Unknown")}
Generated by VerifyFix Critic Agent (generic fallback)
WARNING: This is a generic stub — manual review required.
"""

def test_vulnerability():
    """Generic test stub for {cwe_id}."""
    print("[VULNERABILITY_CONFIRMED] {cwe_id} detected in {vuln.get("file_path", "unknown")} but no automated exploit harness is available for this CWE type.")
    return "VULNERABILITY_CONFIRMED"

if __name__ == "__main__":
    result = test_vulnerability()
    print(f"Final verdict: {{result}}")
    exit(0)
'''
