"""
VerifyFix State Definition
==========================

Defines the strictly typed shared state object (`VerifyFixState`) that flows
through every node in the LangGraph DAG pipeline.  All agents read from and
write to this single state dict, ensuring zero-redundancy token usage and
deterministic data flow.

Phase 2 establishes the schema; downstream phases populate it with real data.
"""

from typing import TypedDict, List, Dict, Any, Optional
import uuid
from datetime import datetime, timezone


# ---------------------------------------------------------------------------
# Sub-type definitions
# ---------------------------------------------------------------------------

class VulnerabilityCandidate(TypedDict):
    """Output schema produced by Agent 1 (Discovery Scanner)."""
    cwe_id: str
    vulnerability_name: str
    file_path: str
    line_start: int
    line_end: int
    suspect_code: str
    reasoning: str


class RemediationItem(TypedDict):
    """Output schema produced by Agent 4 (Senior Analyst)."""
    cwe_id: str
    vulnerability_name: str
    severity: str
    root_cause: str
    patch_diff: str
    defense_in_depth: str
    affected_file: str
    line_range: str


# ---------------------------------------------------------------------------
# Execution step literals
# ---------------------------------------------------------------------------

EXECUTION_STEPS = (
    "INITIALIZED",
    "GITHUB_INGEST",
    "DISCOVERY",
    "RAG",
    "CRITIC",
    "SANDBOX",
    "RETRY",
    "REMEDIATION",
    "COMPLETED",
    "ERROR",
)


# ---------------------------------------------------------------------------
# Core pipeline state
# ---------------------------------------------------------------------------

class VerifyFixState(TypedDict, total=False):
    """
    Shared typed state flowing through every node of the VerifyFix DAG.

    Fields are populated incrementally by each agent/node:
    - ``scan_id``              — Unique scan identifier (UUID).
    - ``repo_owner``           — GitHub repository owner / org.
    - ``repo_name``            — GitHub repository name.
    - ``branch_name``          — Target branch to analyse.
    - ``target_diff``          — Raw unified diff text.
    - ``candidate_vulns``      — Populated by Agent 1 (Discovery).
    - ``rag_context``          — Populated by Layer 2 (ChromaDB RAG).
    - ``pruned_vulns``         — Filtered by Critic Agent Phase I.
    - ``generated_fixtures``   — Test code generated by Critic Agent Phase II.
    - ``docker_status``        — Per-vuln sandbox verdict.
    - ``harness_error_traces`` — Captured stderr for retry loop.
    - ``retry_count``          — Current retry iteration (max 3).
    - ``final_remediations``   — Formatted by Senior Analyst.
    - ``execution_step``       — Active DAG node label.
    - ``logs``                 — Ordered execution log messages.
    - ``started_at``           — ISO timestamp when the scan began.
    - ``completed_at``         — ISO timestamp when the scan finished.
    - ``error``                — Error message if the pipeline failed.
    """
    scan_id: str
    repo_owner: str
    repo_name: str
    branch_name: str
    target_diff: str

    # Agent outputs (populated incrementally)
    candidate_vulns: List[Dict[str, Any]]
    rag_context: Dict[str, str]
    pruned_vulns: List[Dict[str, Any]]
    generated_fixtures: Dict[str, str]
    docker_status: Dict[str, str]
    harness_error_traces: Dict[str, str]
    retry_count: int
    final_remediations: List[Dict[str, Any]]

    # Execution metadata
    execution_step: str
    logs: List[str]
    started_at: str
    completed_at: Optional[str]
    error: Optional[str]


# ---------------------------------------------------------------------------
# Factory
# ---------------------------------------------------------------------------

def create_initial_state(
    repo_owner: str,
    repo_name: str,
    branch_name: str = "main",
    target_diff: str = "",
    scan_id: Optional[str] = None,
) -> VerifyFixState:
    """
    Create a clean initial state dict ready to be fed into the DAG executor.

    Args:
        repo_owner:  GitHub org / username.
        repo_name:   Repository name.
        branch_name: Branch to scan (default ``main``).
        target_diff: Unified diff content to analyse.
        scan_id:     Optional explicit scan ID (auto-generated if omitted).

    Returns:
        A fully-initialised ``VerifyFixState`` dictionary.
    """
    return VerifyFixState(
        scan_id=scan_id or str(uuid.uuid4()),
        repo_owner=repo_owner,
        repo_name=repo_name,
        branch_name=branch_name,
        target_diff=target_diff,
        candidate_vulns=[],
        rag_context={},
        pruned_vulns=[],
        generated_fixtures={},
        docker_status={},
        harness_error_traces={},
        retry_count=0,
        final_remediations=[],
        execution_step="INITIALIZED",
        logs=[],
        started_at=datetime.now(timezone.utc).isoformat(),
        completed_at=None,
        error=None,
    )
